version: '3.8'
services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssqlserver
    environment:
      - MSSQL_SA_PASSWORD=N0rthw1ndpw
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    ports: 
      - 1433:1433  
    volumes:
      - /var/lib/microsoftssql/data 


      